/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon_cloud': '&#xe600;',
		'icon_compose': '&#xe601;',
		'icon_arrow_down': '&#xf03f;',
		'icon_arrow_left': '&#xf040;',
		'icon_arrow_right': '&#xf03e;',
		'icon_arrow_up': '&#xf03d;',
		'icon_book': '&#xf007;',
		'icon_browser': '&#xf0c5;',
		'icon_check': '&#xf03a;',
		'icon_chevron_down': '&#xf0a3;',
		'icon_chevron_left': '&#xf0a4;',
		'icon_chevron_right': '&#xf078;',
		'icon_chevron_up': '&#xf0a2;',
		'icon_circle_slash': '&#xf084;',
		'icon_dash': '&#xf0ca;',
		'icon_list_unordered': '&#xf061;',
		'icon_search': '&#xf02e;',
		'icon_server': '&#xf097;',
		'icon_three_bars': '&#xf05e;',
		'icon_triangle_down': '&#xf05b;',
		'icon_triangle_left': '&#xf044;',
		'icon_triangle_right': '&#xf05a;',
		'icon_triangle_up': '&#xf0aa;',
		'icon_x': '&#xf081;',
		'icon_play': '&#xe912;',
		'icon_drive': '&#xe963;',
		'icon_quotes_left': '&#xe977;',
		'icon_quotes_right': '&#xe978;',
		'icon_loading': '&#xe982;',
		'icon_power_cord': '&#xe9b7;',
		'icon_happy': '&#xe9df;',
		'icon_happy_circle': '&#xe9e0;',
		'icon_smile': '&#xe9e1;',
		'icon_smile_circle': '&#xe9e2;',
		'icon_tongue': '&#xe9e3;',
		'icon_tongue_circle': '&#xe9e4;',
		'icon_sad': '&#xe9e5;',
		'icon_sad_circle': '&#xe9e6;',
		'icon_wink': '&#xe9e7;',
		'icon_wink_circle': '&#xe9e8;',
		'icon_grin': '&#xe9e9;',
		'icon_grin_circle': '&#xe9ea;',
		'icon_cool': '&#xe9eb;',
		'icon_cool_circle': '&#xe9ec;',
		'icon_angry': '&#xe9ed;',
		'icon_angry_circle': '&#xe9ee;',
		'icon_evil': '&#xe9ef;',
		'icon_evil_circle': '&#xe9f0;',
		'icon_shocked': '&#xe9f1;',
		'icon_shocked_circle': '&#xe9f2;',
		'icon_baffled': '&#xe9f3;',
		'icon_baffled_circle': '&#xe9f4;',
		'icon_confused': '&#xe9f5;',
		'icon_confused_circle': '&#xe9f6;',
		'icon_neutral': '&#xe9f7;',
		'icon_neutral_circle': '&#xe9f8;',
		'icon_hipster': '&#xe9f9;',
		'icon_hipster_circle': '&#xe9fa;',
		'icon_wondering': '&#xe9fb;',
		'icon_wondering_circle': '&#xe9fc;',
		'icon_sleepy': '&#xe9fd;',
		'icon_sleepy_circle': '&#xe9fe;',
		'icon_frustrated': '&#xe9ff;',
		'icon_frustrated_circle': '&#xea00;',
		'icon_crying': '&#xea01;',
		'icon_crying_circle': '&#xea02;',
		'icon_skype1': '&#xeac6;',
		'icon_linkedin1': '&#xeac8;',
		'icon_chrome': '&#xeae5;',
		'icon_firefox': '&#xeae6;',
		'icon_ie': '&#xeae7;',
		'icon_safari': '&#xeae9;',
		'icon_icomoon': '&#xeaea;',
		'icon_window': '&#xe602;',
		'icon_hardware': '&#xe62e;',
		'icon_phone': '&#xe603;',
		'icon_tablet': '&#xe604;',
		'icon_monitor': '&#xe605;',
		'icon_picture': '&#xe606;',
		'icon_pictures': '&#xe607;',
		'icon_marvin': '&#xe62a;',
		'icon_cloud2': '&#xe608;',
		'icon_phone2': '&#xe609;',
		'icon_smiley': '&#xe60a;',
		'icon_sad3': '&#xe60b;',
		'icon_mute': '&#xe60c;',
		'icon_locked': '&#xe62b;',
		'icon_stats': '&#xe60d;',
		'icon_loop': '&#xe62f;',
		'icon_clipboard': '&#xe60e;',
		'icon_group': '&#xe60f;',
		'icon_dns': '&#xe62c;',
		'icon_message': '&#xe610;',
		'icon_chevron_left2': '&#xe611;',
		'icon_chevron_right2': '&#xe612;',
		'icon_expand_top': '&#xe613;',
		'icon_expand_bottom': '&#xe614;',
		'icon_publ': '&#xe615;',
		'icon_qrcode': '&#xf029;',
		'icon_spinner': '&#xf110;',
		'icon_apple': '&#xf179;',
		'icon_windows': '&#xf17a;',
		'icon_android': '&#xf17b;',
		'icon_linux': '&#xf17c;',
		'icon_bug': '&#xf188;',
		'icon_weibo': '&#xf18a;',
		'icon_renren': '&#xf18b;',
		'icon_paw': '&#xf1b0;',
		'icon_qq': '&#xf1d6;',
		'icon_wechat': '&#xf1d7;',
		'icon_user': '&#xe616;',
		'icon_users': '&#xe617;',
		'icon_browser2': '&#xe62d;',
		'icon_database': '&#xe618;',
		'icon_cart': '&#xe619;',
		'icon_info': '&#xe61a;',
		'icon_disk': '&#xe630;',
		'icon_github': '&#xe61b;',
		'icon_flickr': '&#xe61c;',
		'icon_vimeo': '&#xe61d;',
		'icon_twitter': '&#xe61e;',
		'icon_facebook': '&#xe61f;',
		'icon_googleplus': '&#xe620;',
		'icon_pinterest': '&#xe621;',
		'icon_tumblr': '&#xe622;',
		'icon_linkedin': '&#xe623;',
		'icon_dribbble': '&#xe624;',
		'icon_stumbleupon': '&#xe625;',
		'icon_lastfm': '&#xe626;',
		'icon_qq2': '&#xe627;',
		'icon_skype': '&#xe628;',
		'icon_vk': '&#xe629;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon_[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
